class KnowledgeBase():
    def __init__(self) -> None:
        self.kb = self.get_kb_dict()
    
    def get_kb_dict(self):
        kb = [
            {
                'label': 'Chemical Engineering and Chemistry',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses' : 'yes',
                'IB': [['Mathematics HL', 'Physics HL', 'Chemistry SL'],
                       ['Mathematics HL', 'Physics SL', 'Chemistry HL'],
                       ['Mathematics HL', 'Physics HL', 'Chemistry HL']],
                'AP': [['Calculus A/B', 'Physics 1', 'Chemistry'],
                        ['Calculus A/B', 'Physics 2', 'Chemistry'],
                        ['Calculus A/B', 'Physics C', 'Chemistry'],
                        ['Calculus B/C', 'Physics 1', 'Chemistry'],
                        ['Calculus B/C', 'Physics 2', 'Chemistry'],
                        ['Calculus B/C', 'Physics C', 'Chemistry']],
                'Calculus A/B': 3,
                'Calculus B/C': 3, 
                'Physics 1': 3,
                'Physics 2': 3,
                'Physics C': 3,
                'Chemistry': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0], ['Writing', 6.0]],
                'CPE' : [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE' : [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Chemical Engineering', 'Chemistry', 'Sustainable Energy', 'Health', 'Material Science', 'Process Engineering', 'Process Technology', 'Design'],
                'multidisciplinary': 'yes',
                'enterance exam': 'no',
                'study choice check': 'yes',
                # The outcome of the study choice check is not binding and does not influence your admission to the program. Consider the study choice check as a useful way to prepare yourself for starting your Bachelor's program at TU/e.
                'research': 'yes',
                'practical oriented': 'yes',
                'project oriented': 'no',
            },
            {
                'label': 'Electrical Engineering',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses' : 'yes',
                'IB': ['Mathematics HL', 'Physics HL'],
                'AP': [['Calculus A/B', 'Physics 1'],
                        ['Calculus A/B', 'Physics 2'],
                        ['Calculus A/B', 'Physics C'],
                        ['Calculus B/C', 'Physics 1'],
                        ['Calculus B/C', 'Physics 2'],
                        ['Calculus B/C', 'Physics C']],
                'Calculus A/B': 3,
                'Calculus B/C': 3, 
                'Physics 1': 3,
                'Physics 2': 3,
                'Physics C': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0], ['Writing', 6.0]],
                'CPE' : [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE' : [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Electrical Engineering', 'Electricity', 'Magnetism', 'Communication', 'Healthcare', 'Environment', 'Smart and Sustainable Society'],
                'multidisciplinary': 'no',
                'enterance exam': 'no',
                'study choice check': 'yes',
                'research': 'no',
                'practical oriented': 'no',
                'project oriented': 'no',
            },
            {
                'label': 'Architecture, Urbanism and Building',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses' : 'yes',
                'IB': ['Mathematics HL', 'Physics HL'],
                'AP': [['Calculus A/B', 'Physics 1'],
                        ['Calculus A/B', 'Physics 2'],
                        ['Calculus A/B', 'Physics C'],
                        ['Calculus B/C', 'Physics 1'],
                        ['Calculus B/C', 'Physics 2'],
                        ['Calculus B/C', 'Physics C']],
                'Calculus A/B': 3,
                'Calculus B/C': 3, 
                'Physics 1': 3,
                'Physics 2': 3,
                'Physics C': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0], ['Writing', 6.0]],
                'CPE' : [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE' : [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Architecture', 'Urbanism', 'Building Sciences', 'Structural Design', 'Real Estate', 'Innovative', 'Creativity'],
                'multidisciplinary': 'yes',
                'enterance exam': 'yes',
                'study choice check': 'no',
                'research': 'no',
                'practical oriented': 'no',
                'project oriented': 'yes',
            },
            {
                'label': 'Automative Techonology',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses' : 'yes',
                'IB': ['Mathematics HL', 'Physics HL'],
                'AP': [['Calculus A/B', 'Physics 1'],
                        ['Calculus A/B', 'Physics 2'],
                        ['Calculus A/B', 'Physics C'],
                        ['Calculus B/C', 'Physics 1'],
                        ['Calculus B/C', 'Physics 2'],
                        ['Calculus B/C', 'Physics C']],
                'Calculus A/B': 3,
                'Calculus B/C': 3, 
                'Physics 1': 3,
                'Physics 2': 3,
                'Physics C': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0], ['Writing', 6.0]],
                'CPE' : [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE' : [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Automative Technology', 'Cars', 'High-tech Systems', 'Electronics', 'Software'],
                'multidisciplinary': 'no',
                'enterance exam': 'no',
                'study choice check': 'yes',
                'research': 'no',
                'practical oriented': 'no',
                'project oriented': 'no',
            },
            {
                'label': 'Mechanical Engineering',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses' : 'yes',
                'IB': ['Mathematics HL', 'Physics HL'],
                'AP': [['Calculus A/B', 'Physics 1'],
                        ['Calculus A/B', 'Physics 2'],
                        ['Calculus A/B', 'Physics C'],
                        ['Calculus B/C', 'Physics 1'],
                        ['Calculus B/C', 'Physics 2'],
                        ['Calculus B/C', 'Physics C']],
                'Calculus A/B': 3,
                'Calculus B/C': 3, 
                'Physics 1': 3,
                'Physics 2': 3,
                'Physics C': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0], ['Writing', 6.0]],
                'CPE' : [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE' : [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Mechanical Engineering', 'Mathematics', 'Physics', 'Chemistry', 'Innovation', 'Creativity'],
                'multidisciplinary': 'yes',
                'enterance exam': 'yes',
                'study choice check': 'no',
                'research': 'no',
                'practical oriented': 'no',
                'project oriented': 'yes',
            },
            {
                'label': 'Sustainable Innovation',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses' : 'yes',
                'IB': ['Mathematics HL'],
                'AP': [['Calculus A/B'], 
                       ['Calculus B/C']],
                'Calculus A/B': 3,
                'Calculus B/C': 3, 
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0], ['Writing', 6.0]],
                'CPE' : [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE' : [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Innovation', 'Sustainability', 'Environment', 'Climate', 'Economics', 'Social Sciences', 'Technology', 'Society'],
                'multidisciplinary': 'yes',
                'enterance exam': 'no',
                'study choice check': 'yes',
                'research': 'no',
                'practical oriented': 'no',
                'project oriented': 'no',
            },
            {
                'label': 'Industrial Engineering',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses' : 'yes',
                'IB': ['Mathematics HL'],
                'AP': [['Calculus A/B'], 
                       ['Calculus B/C']],
                'Calculus A/B': 3,
                'Calculus B/C': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0], ['Writing', 6.0]],
                'CPE' : [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE' : [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Industrial Engineering', 'Business', 'Management', 'Technology', 'Production', 'Information Systems', 'Organization'],
                'multidisciplinary': 'no',
                'enterance exam': 'no',
                'study choice check': 'no',
                'research': 'yes',
                'practical oriented': 'yes',
                'project oriented': 'no',
            },
                        {
                'label': 'Computer Science and Engineering',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses' : 'yes',
                'IB': ['Mathematics HL'],
                'AP': [['Calculus A/B'], 
                       ['Calculus B/C']],
                'Calculus A/B': 3,
                'Calculus B/C': 3, 
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0], ['Writing', 6.0]],
                'CPE' : [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE' : [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Computer Science', 'Software Systems', 'Design', 'Web Services', 'Technology'],
                'multidisciplinary': 'no',
                'enterance exam': 'yes',
                'study choice check': 'no',
                'research': 'no',
                'practical oriented': 'no',
                'project oriented': 'no', 
            },
            {
                'label': 'Psychology & Technology',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses' : 'yes',
                'IB': ['Mathematics HL'],
                'AP': [['Calculus A/B'], 
                       ['Calculus B/C']],
                'AP grades' : 'yes',
                'Calculus A/B': 3,
                'Calculus B/C': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0], ['Writing', 6.0]],
                'CPE' : [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE' : [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Psychology', 'Technology', 'Robots', 'Society', 'Design'],
                'multidisciplinary': 'yes',
                'enterance exam': 'no',
                'study choice check': 'yes',
                'research': 'yes',
                'practical oriented': 'yes', # hands-on/lab experience
                'project oriented': 'no',
            },
        ]
        return kb
