class KnowledgeBase:
    def __init__(self) -> None:
        self.kb = self.get_kb_dict()
        self.user_kb = {}

    @staticmethod
    def get_kb_dict():
        kb = [

            # EINDHOVEN UNIVERSITY
            {
                'label': 'Chemical Engineering and Chemistry',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL', 'Physics HL', 'Chemistry SL'],
                       ['Analysis & Approaches HL', 'Physics SL', 'Chemistry HL'],
                       ['Analysis & Approaches HL', 'Physics HL', 'Chemistry HL'],
                       ['Mathematics HL', 'Physics HL', 'Chemistry SL'],
                       ['Mathematics HL', 'Physics SL', 'Chemistry HL'],
                       ['Mathematics HL', 'Physics HL', 'Chemistry HL']],
                'AP': [['Calculus A/B', 'Physics 1', 'Chemistry'],
                       ['Calculus A/B', 'Physics 2', 'Chemistry'],
                       ['Calculus A/B', 'Physics C Mechanics', 'Chemistry'],
                       ['Calculus B/C', 'Physics 1', 'Chemistry'],
                       ['Calculus B/C', 'Physics 2', 'Chemistry'],
                       ['Calculus B/C', 'Physics C Mechanics', 'Chemistry']],
                'Calculus A/B': 3,
                'Calculus B/C': 3,
                'Physics 1': 3,
                'Physics 2': 3,
                'Physics C Mechanics': 3,
                'Chemistry': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0],
                                     ['Writing', 6.0]],
                'CPE': [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE': [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Chemical Engineering', 'Chemistry', 'Sustainability', 'Healthcare', 'Material Science',
                          'Process Engineering', 'Design'],
                'multidisciplinary': 'yes',
                'enterance exam': 'no',
                'study choice check': 'yes',
                # The outcome of the study choice check is not binding and does not influence your admission to the program. Consider the study choice check as a useful way to prepare yourself for starting your Bachelor's program at TU/e.
                'research': 'yes',
                'practical oriented': 'yes',
                'project oriented': 'no',
                'numerus fixus': 'no',
            },
            {
                'label': 'Electrical Engineering',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL', 'Physics HL'],
                       ['Mathematics HL', 'Physics HL']],
                'AP': [['Calculus A/B', 'Physics 1'],
                       ['Calculus A/B', 'Physics 2'],
                       ['Calculus A/B', 'Physics C Mechanics'],
                       ['Calculus B/C', 'Physics 1'],
                       ['Calculus B/C', 'Physics 2'],
                       ['Calculus B/C', 'Physics C Mechanics']],
                'Calculus A/B': 3,
                'Calculus B/C': 3,
                'Physics 1': 3,
                'Physics 2': 3,
                'Physics C Mechanics': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0],
                                     ['Writing', 6.0]],
                'CPE': [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE': [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Electrical Engineering', 'Electricity', 'Magnetism', 'Healthcare',
                          'Environment', 'Sustainability', 'Society'],
                'multidisciplinary': 'no',
                'enterance exam': 'no',
                'study choice check': 'yes',
                'research': 'no',
                'practical oriented': 'no',
                'project oriented': 'no',
                'numerus fixus': 'no',
            },
            {
                'label': 'Architecture, Urbanism and Building',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL', 'Physics HL'],
                       ['Mathematics HL', 'Physics HL']],
                'AP': [['Calculus A/B', 'Physics 1'],
                       ['Calculus A/B', 'Physics 2'],
                       ['Calculus A/B', 'Physics C Mechanics'],
                       ['Calculus B/C', 'Physics 1'],
                       ['Calculus B/C', 'Physics 2'],
                       ['Calculus B/C', 'Physics C Mechanics']],
                'Calculus A/B': 3,
                'Calculus B/C': 3,
                'Physics 1': 3,
                'Physics 2': 3,
                'Physics C Mechanics': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0],
                                     ['Writing', 6.0]],
                'CPE': [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE': [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Architecture', 'Building Sciences', 'Design', 'Real Estate',
                          'Innovation', 'Creativity'],
                'multidisciplinary': 'yes',
                'enterance exam': 'yes',
                'study choice check': 'no',
                'research': 'no',
                'practical oriented': 'no',
                'project oriented': 'yes',
                'numerus fixus': 'no',
            },
            {
                'label': 'Automative Techonology',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL', 'Physics HL'],
                       ['Mathematics HL', 'Physics HL']],
                'AP': [['Calculus A/B', 'Physics 1'],
                       ['Calculus A/B', 'Physics 2'],
                       ['Calculus A/B', 'Physics C Mechanics'],
                       ['Calculus B/C', 'Physics 1'],
                       ['Calculus B/C', 'Physics 2'],
                       ['Calculus B/C', 'Physics C Mechanics']],
                'Calculus A/B': 3,
                'Calculus B/C': 3,
                'Physics 1': 3,
                'Physics 2': 3,
                'Physics C Mechanics': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0],
                                     ['Writing', 6.0]],
                'CPE': [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE': [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Automative Technology', 'Cars', 'Electronics', 'Software'],
                'multidisciplinary': 'no',
                'enterance exam': 'no',
                'study choice check': 'yes',
                'research': 'no',
                'practical oriented': 'no',
                'project oriented': 'no',
                'numerus fixus': 'no',
            },
            {
                'label': 'Mechanical Engineering',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL', 'Physics HL'],
                       ['Mathematics HL', 'Physics HL']],
                'AP': [['Calculus A/B', 'Physics 1'],
                       ['Calculus A/B', 'Physics 2'],
                       ['Calculus A/B', 'Physics C Mechanics'],
                       ['Calculus B/C', 'Physics 1'],
                       ['Calculus B/C', 'Physics 2'],
                       ['Calculus B/C', 'Physics C Mechanics']],
                'Calculus A/B': 3,
                'Calculus B/C': 3,
                'Physics 1': 3,
                'Physics 2': 3,
                'Physics C Mechanics': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0],
                                     ['Writing', 6.0]],
                'CPE': [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE': [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Mechanical Engineering', 'Mathematics', 'Physics', 'Chemistry', 'Innovation', 'Creativity'],
                'multidisciplinary': 'yes',
                'enterance exam': 'yes',
                'study choice check': 'no',
                'research': 'no',
                'practical oriented': 'no',
                'project oriented': 'yes',
                'numerus fixus': 'no',
            },
            {
                'label': 'Sustainable Innovation',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL'],
                       ['Mathematics HL']],
                'AP': [['Calculus A/B'],
                       ['Calculus B/C']],
                'Calculus A/B': 3,
                'Calculus B/C': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0],
                                     ['Writing', 6.0]],
                'CPE': [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE': [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Innovation', 'Sustainability', 'Environment', 'Climate', 'Economics', 'Social Sciences',
                          'Technology', 'Society'],
                'multidisciplinary': 'yes',
                'enterance exam': 'no',
                'study choice check': 'yes',
                'research': 'no',
                'practical oriented': 'no',
                'project oriented': 'no',
                'numerus fixus': 'no',
            },
            {
                'label': 'Industrial Engineering',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL'],
                       ['Mathematics HL']],
                'AP': [['Calculus A/B'],
                       ['Calculus B/C']],
                'Calculus A/B': 3,
                'Calculus B/C': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0],
                                     ['Writing', 6.0]],
                'CPE': [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE': [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Industrial Engineering', 'Business', 'Management', 'Technology', 'Production',
                          'Information Systems'],
                'multidisciplinary': 'no',
                'enterance exam': 'no',
                'study choice check': 'no',
                'research': 'yes',
                'practical oriented': 'yes',
                'project oriented': 'no',
                'numerus fixus': 'no',
            },
            {
                'label': 'Computer Science and Engineering',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL'],
                       ['Mathematics HL']],
                'AP': [['Calculus A/B'],
                       ['Calculus B/C']],
                'Calculus A/B': 3,
                'Calculus B/C': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0],
                                     ['Writing', 6.0]],
                'CPE': [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE': [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Computer Science', 'Software', 'Programming', 'Design', 'Internet', 'Technology'],
                'multidisciplinary': 'no',
                'enterance exam': 'yes',
                'study choice check': 'no',
                'research': 'no',
                'practical oriented': 'no',
                'project oriented': 'no',
                'numerus fixus': 'no',
            },
            {
                'label': 'Psychology & Technology',
                'university': 'Technical University of Eindhoven',
                'city': 'Eindhoven',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL'],
                       ['Mathematics HL']],
                'AP': [['Calculus A/B'],
                       ['Calculus B/C']],
                'Calculus A/B': 3,
                'Calculus B/C': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 21]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.0], ['Listening', 6.0], ['Speaking', 6.0],
                                     ['Writing', 6.0]],
                'CPE': [['overall', 180], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'CAE': [['overall', 176], ['Reading', 169], ['Listening', 169], ['Speaking', 169], ['Writing', 169]],
                'about': ['Psychology', 'Technology', 'Robots', 'Society', 'Design'],
                'multidisciplinary': 'yes',
                'enterance exam': 'no',
                'study choice check': 'yes',
                'research': 'yes',
                'practical oriented': 'yes',  # hands-on/lab experience
                'project oriented': 'no',
                'numerus fixus': 'no',
            },

            # UNIVERSITY OF GRONINGEN
            {
                'label': 'Chemical Engineering',
                'university': 'University of Groningen',
                'city': 'Groningen',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL', 'Physics HL', 'Chemistry SL'],
                       ['Analysis & Approaches HL', 'Physics SL', 'Chemistry HL'],
                       ['Analysis & Approaches HL', 'Physics HL', 'Chemistry HL'],
                       ['Mathematics HL', 'Physics HL', 'Chemistry SL'],
                       ['Mathematics HL', 'Physics SL', 'Chemistry HL'],
                       ['Mathematics HL', 'Physics HL', 'Chemistry HL']],
                'AP': [['Calculus A/B', 'Physics 2', 'Chemistry'],
                       ['Calculus B/C', 'Physics 2', 'Chemistry']],
                'Calculus A/B': 3,
                'Calculus B/C': 3,
                'Physics 2': 3,
                'Chemistry': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 24]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.5], ['Listening', 6.5], ['Speaking', 6.5],
                                     ['Writing', 6.5]],
                'CPE': [['overall', 180]],
                'CAE': [['overall', 180]],
                'about': ['Chemical Engineering', 'Chemistry', 'Sustainability', 'Process Engineering', 'Design'],
                'multidisciplinary': 'yes',
                'enterance exam': 'no',
                'study choice check': 'yes',  # matching
                'research': 'yes',
                'practical oriented': 'yes',  # hands-on/lab experience
                'project oriented': 'no',
                'numerus fixus': 'no',
            },
            {
                'label': 'Industrial Engineering & Management',
                'university': 'University of Groningen',
                'city': 'Groningen',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL', 'Physics HL'],
                       ['Mathematics HL', 'Physics HL']],
                'AP': [['Calculus A/B', 'Physics 2'],
                       ['Calculus B/C', 'Physics 2']],
                'Calculus A/B': 3,
                'Calculus B/C': 3,
                'Physics 2': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 24]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.5], ['Listening', 6.5], ['Speaking', 6.5],
                                     ['Writing', 6.5]],
                'CPE': [['overall', 180]],
                'CAE': [['overall', 180]],
                'about': ['Industrial Engineering', 'Design', 'Business', 'Management', 'Technology', 'Production'],
                'multidisciplinary': 'yes',
                'enterance exam': 'no',
                'study choice check': 'yes',  # matching
                'research': 'yes',
                'practical oriented': 'no',  # hands-on/lab experience
                'project oriented': 'yes',
                'numerus fixus': 'no',
            },
            {
                'label': 'Biomedical Engineering',
                'university': 'University of Groningen',
                'city': 'Groningen',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL', 'Physics HL'],
                       ['Mathematics HL', 'Physics HL']],
                'AP': [['Calculus A/B', 'Physics 2'],
                       ['Calculus B/C', 'Physics 2']],
                'Calculus A/B': 3,
                'Calculus B/C': 3,
                'Physics 2': 3,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90], ['Reading', 21], ['Listening', 21], ['Speaking', 21], ['Writing', 24]],
                'IELTS (academic)': [['overall', 6.5], ['Reading', 6.5], ['Listening', 6.5], ['Speaking', 6.5],
                                     ['Writing', 6.5]],
                'CPE': [['overall', 180]],
                'CAE': [['overall', 180]],
                'about': ['Biomedical Engineering', 'Healthcare', 'Biology', 'Sustainability', 'Innovation', 'Design'],
                'multidisciplinary': 'yes',
                'enterance exam': 'yes',
                'study choice check': 'yes',  # matching
                'research': 'no',
                'practical oriented': 'yes',  # hands-on/lab experience
                'project oriented': 'no',
                'numerus fixus': 'yes',
                # has different requirements from depending on uni, RUG required test & portfolio
            },

            # MAASTRICHT UNIVERSITY
            {
                'label': 'Circular Engineering',
                'university': 'Maastricht University',
                'city': 'Maastricht',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'no',
                'IB': [['Analysis & Approaches HL', 'Physics HL', 'Chemistry SL'],
                       ['Analysis & Approaches HL', 'Physics SL', 'Chemistry HL'],
                       ['Analysis & Approaches HL', 'Physics HL', 'Chemistry HL'],
                       ['Analysis & Approaches HL', 'Physics SL', 'Chemistry SL'],
                       ['Mathematics HL', 'Physics HL', 'Chemistry SL'],
                       ['Mathematics HL', 'Physics SL', 'Chemistry HL'],
                       ['Mathematics HL', 'Physics HL', 'Chemistry HL'],
                       ['Mathematics HL', 'Physics SL', 'Chemistry SL'],
                       ['Mathematics SL', 'Physics HL', 'Chemistry SL'],
                       ['Mathematics SL', 'Physics SL', 'Chemistry HL'],
                       ['Mathematics SL', 'Physics HL', 'Chemistry HL'],
                       ['Mathematics SL', 'Physics SL', 'Chemistry SL'],
                       ['Analysis & Approaches HL', 'Physics HL', 'Biology SL'],
                       ['Analysis & Approaches HL', 'Physics SL', 'Biology HL'],
                       ['Analysis & Approaches HL', 'Physics HL', 'Biology HL'],
                       ['Analysis & Approaches HL', 'Physics SL', 'Biology SL'],
                       ['Mathematics HL', 'Physics HL', 'Biology SL'],
                       ['Mathematics HL', 'Physics SL', 'Biology HL'],
                       ['Mathematics HL', 'Physics HL', 'Biology HL'],
                       ['Mathematics HL', 'Physics SL', 'Biology SL'],
                       ['Mathematics SL', 'Physics HL', 'Biology SL'],
                       ['Mathematics SL', 'Physics SL', 'Biology HL'],
                       ['Mathematics SL', 'Physics HL', 'Biology HL'],
                       ['Mathematics SL', 'Physics SL', 'Biology SL']],
                'Mathematics SL': 5,
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 80]],
                'IELTS (academic)': [['overall', 6.0]],
                'CPE': [['overall', 180]],
                'CAE': [['overall', 180]],
                'about': ['Circular Engineering', 'Economics', 'Environment', 'Sustainability',
                          'Innovation', 'Design'],
                'multidisciplinary': 'no',
                'enterance exam': 'no',
                'study choice check': 'no',
                'research': 'yes',
                'practical oriented': 'yes',  # hands-on/lab experience
                'project oriented': 'yes',
                'numerus fixus': 'no',
                # has different requirements from depending on uni, RUG required test & portfolio
            },
            {
                'label': 'Business Engineering',
                'university': 'Maastricht University',
                'city': 'Maastricht',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'no',
                'IB': [['Analysis & Approaches HL'],
                       ['Mathematics HL'],
                       ['Analysis & Approaches SL'],
                       ['Mathematics SL']],
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 80]],
                'IELTS (academic)': [['overall', 6.0]],
                'CPE': [['overall', 180]],
                'CAE': [['overall', 180]],
                'about': ['Mathematics', 'Business', 'Economics', 'Society', 'Technology', 'Innovation'],
                'multidisciplinary': 'no',
                'enterance exam': 'no',
                'study choice check': 'no',
                'research': 'no',
                'practical oriented': 'no',  # hands-on/lab experience
                'project oriented': 'no',
                'numerus fixus': 'no',
                # has different requirements from depending on uni, RUG required test & portfolio
            },

            # DELFT UNIVERSITY
            {
                'label': 'Aerospace Engineering',
                'university': 'Delft University of Technology (TU Delft)',
                'city': 'Delft',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': ['Analysis & Approaches HL', 'Physics HL'],
                'AP': [['Calculus A/B', 'Physics 1'],
                       ['Calculus A/B', 'Physics 2'],
                       ['Calculus A/B', 'Physics C Mechanics'],
                       ['Calculus B/C', 'Physics 1'],
                       ['Calculus B/C', 'Physics 2'],
                       ['Calculus B/C', 'Physics C Mechanics']],
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90]],
                'IELTS (academic)': [['overall', 6.5]],
                'CPE': [['overall', 180]],
                'CAE': [['overall', 176]],
                'about': ['Aerospace', 'Technology', 'Innovation', 'Design'],
                'multidisciplinary': 'yes',
                'enterance exam': 'no',
                'study choice check': 'no',
                'research': 'no',
                'practical oriented': 'no',  # hands-on/lab experience
                'project oriented': 'no',
                'numerus fixus': 'yes',
                # has different requirements from depending on uni, RUG required test & portfolio
            },
            {
                'label': 'Computer Science & Engineering',
                'university': 'Delft University of Technology (TU Delft)',
                'city': 'Delft',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': ['Analysis & Approaches HL'],
                'AP': [['Calculus A/B'],
                       ['Calculus B/C']],
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 90]],
                'IELTS (academic)': [['overall', 6.5]],
                'CPE': [['overall', 180]],
                'CAE': [['overall', 176]],
                'about': ['Computer Science', 'Software', 'Mathematics', 'Programming', 'Technology',
                          'Data Processing'],
                'multidisciplinary': 'no',
                'enterance exam': 'no',
                'study choice check': 'no',
                'research': 'no',
                'practical oriented': 'no',  # hands-on/lab experience
                'project oriented': 'no',
                'numerus fixus': 'no',
                # has different requirements from depending on uni, RUG required test & portfolio
            },

            # TWENTE UNIVERSITY
            {
                'label': 'Chemical Science & Engineering',
                'university': 'University of Twente',
                'city': 'Enschede',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL', 'Physics HL', 'Chemistry SL', 'English HL'],
                       ['Analysis & Approaches HL', 'Physics SL', 'Chemistry HL', 'English HL'],
                       ['Analysis & Approaches HL', 'Physics HL', 'Chemistry HL', 'English HL'],
                       ['Mathematics HL', 'Physics HL', 'Chemistry SL', 'English HL'],
                       ['Mathematics HL', 'Physics SL', 'Chemistry HL', 'English HL'],
                       ['Mathematics HL', 'Physics HL', 'Chemistry HL', 'English HL'],
                       ['Analysis & Approaches HL', 'Physics HL', 'Chemistry SL', 'English SL'],
                       ['Analysis & Approaches HL', 'Physics SL', 'Chemistry HL', 'English SL'],
                       ['Analysis & Approaches HL', 'Physics HL', 'Chemistry HL', 'English SL'],
                       ['Mathematics HL', 'Physics HL', 'Chemistry SL', 'English SL'],
                       ['Mathematics HL', 'Physics SL', 'Chemistry HL', 'English SL'],
                       ['Mathematics HL', 'Physics HL', 'Chemistry HL', 'English SL']],
                'AP': [['Calculus A/B', 'Physics C Mechanics', 'Chemistry'],
                       ['Calculus A/B', 'Physics C  Electricity and Magnetism', 'Chemistry'],
                       ['Calculus B/C', 'Physics C Mechanics', 'Chemistry'],
                       ['Calculus B/C', 'Physics C  Electricity and Magnetism', 'Chemistry']],
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 80]],
                'IELTS (academic)': [['overall', 6.0]],
                'CPE': [['overall', 200]],
                'CAE': [['overall', 180]],
                'about': ['Chemical Engineering', 'Mathematics', 'Physics', 'Chemistry', 'Material Science',
                          'Process Engineering'],
                'multidisciplinary': 'no',
                'enterance exam': 'no',
                'study choice check': 'no',
                'research': 'yes',
                'practical oriented': 'no',  # hands-on/lab experience
                'project oriented': 'no',
                'numerus fixus': 'no',
            },
            {
                'label': 'Civil Engineering',
                'university': 'University of Twente',
                'city': 'Enschede',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL', 'Physics HL', 'English HL'],
                       ['Analysis & Approaches HL', 'Physics SL', 'English HL'],
                       ['Mathematics HL', 'Physics HL', 'English HL'],
                       ['Mathematics HL', 'Physics SL', 'English HL'],
                       ['Analysis & Approaches HL', 'Physics HL', 'English SL'],
                       ['Analysis & Approaches HL', 'Physics SL', 'English SL'],
                       ['Mathematics HL', 'Physics HL', 'English SL'],
                       ['Mathematics HL', 'Physics SL', 'English SL']],
                'AP': [['Calculus A/B', 'Physics C Mechanics'],
                       ['Calculus A/B', 'Physics C  Electricity and Magnetism'],
                       ['Calculus B/C', 'Physics C Mechanics'],
                       ['Calculus B/C', 'Physics C  Electricity and Magnetism']],
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 80]],
                'IELTS (academic)': [['overall', 6.0]],
                'CPE': [['overall', 200]],
                'CAE': [['overall', 180]],
                'about': ['Civil Engineering', 'Environment', 'Business', 'Society', 'Technology', 'Management',
                          'Design', 'Building Sciences', 'Transport'],
                'multidisciplinary': 'no',
                'enterance exam': 'no',
                'study choice check': 'no',
                'research': 'no',
                'practical oriented': 'no',  # hands-on/lab experience
                'project oriented': 'yes',
                'numerus fixus': 'no',
            },
            {
                'label': 'Electrical Engineering',
                'university': 'University of Twente',
                'city': 'Enschede',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL', 'Physics HL', 'English HL'],
                       ['Analysis & Approaches HL', 'Physics SL', 'English HL'],
                       ['Mathematics HL', 'Physics HL', 'English HL'],
                       ['Mathematics HL', 'Physics SL', 'English HL'],
                       ['Analysis & Approaches HL', 'Physics HL', 'English SL'],
                       ['Analysis & Approaches HL', 'Physics SL', 'English SL'],
                       ['Mathematics HL', 'Physics HL', 'English SL'],
                       ['Mathematics HL', 'Physics SL', 'English SL']],
                'AP': [['Calculus A/B', 'Physics C Mechanics'],
                       ['Calculus A/B', 'Physics C  Electricity and Magnetism'],
                       ['Calculus B/C', 'Physics C Mechanics'],
                       ['Calculus B/C', 'Physics C  Electricity and Magnetism']],
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 80]],
                'IELTS (academic)': [['overall', 6.0]],
                'CPE': [['overall', 200]],
                'CAE': [['overall', 180]],
                'about': ['Electrical Engineering', 'Robots', 'Electricity', 'Physics'],
                'multidisciplinary': 'no',
                'enterance exam': 'no',
                'study choice check': 'no',
                'research': 'yes',
                'practical oriented': 'no',  # hands-on/lab experience
                'project oriented': 'no',
                'numerus fixus': 'no',
            },
            {
                'label': 'Industrial Design Engineering',
                'university': 'University of Twente',
                'city': 'Enschede',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL', 'Physics HL', 'English HL'],
                       ['Analysis & Approaches HL', 'Physics SL', 'English HL'],
                       ['Mathematics HL', 'Physics HL', 'English HL'],
                       ['Mathematics HL', 'Physics SL', 'English HL'],
                       ['Analysis & Approaches HL', 'Physics HL', 'English SL'],
                       ['Analysis & Approaches HL', 'Physics SL', 'English SL'],
                       ['Mathematics HL', 'Physics HL', 'English SL'],
                       ['Mathematics HL', 'Physics SL', 'English SL']],
                'AP': [['Calculus A/B', 'Physics C Mechanics'],
                       ['Calculus A/B', 'Physics C  Electricity and Magnetism'],
                       ['Calculus B/C', 'Physics C Mechanics'],
                       ['Calculus B/C', 'Physics C  Electricity and Magnetism']],
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 80]],
                'IELTS (academic)': [['overall', 6.0]],
                'CPE': [['overall', 200]],
                'CAE': [['overall', 180]],
                'about': ['Industrial Engineering', 'Technology', 'Design', 'Creativity', 'Innovation', 'Production',
                          'Graphic Design', 'Marketing'],
                'multidisciplinary': 'no',
                'enterance exam': 'no',
                'study choice check': 'no',
                'research': 'no',
                'practical oriented': 'yes',  # hands-on/lab experience
                'project oriented': 'yes',
                'numerus fixus': 'no',
            },
            {
                'label': 'Industrial Engineering & Management Science',
                'university': 'University of Twente',
                'city': 'Enschede',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL', 'English HL'],
                       ['Mathematics HL', 'English HL'],
                       ['Analysis & Approaches HL', 'English SL'],
                       ['Mathematics HL', 'English SL']],
                'AP': [['Calculus A/B'],
                       ['Calculus B/C']],
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 80]],
                'IELTS (academic)': [['overall', 6.0]],
                'CPE': [['overall', 200]],
                'CAE': [['overall', 180]],
                'about': ['Industrial Engineering', 'Business Engineering', 'Technical', 'Business', 'Society',
                          'Mathematics', 'Technology', 'Healthcare'],
                'multidisciplinary': 'no',
                'enterance exam': 'no',
                'study choice check': 'no',
                'research': 'no',
                'practical oriented': 'yes',  # hands-on/lab experience
                'project oriented': 'yes',
                'numerus fixus': 'no',
            },
            {
                'label': 'Mechanical Engineering',
                'university': 'University of Twente',
                'city': 'Enschede',
                'degree': 'Bachelor of Science',
                'duration': '3',
                'diplomas': ['IB', 'Lise Diploma', 'Label France Education', 'Abitur'],
                'AP courses': 'yes',
                'IB': [['Analysis & Approaches HL', 'Physics HL', 'English HL'],
                       ['Mathematics HL', 'Physics HL', 'English HL'],
                       ['Analysis & Approaches HL', 'Physics HL', 'English SL'],
                       ['Mathematics HL', 'Physics HL', 'English SL']],
                'AP': [['Calculus A/B', 'Physics C Mechanics'],
                       ['Calculus A/B', 'Physics C  Electricity and Magnetism'],
                       ['Calculus B/C', 'Physics C Mechanics'],
                       ['Calculus B/C', 'Physics C  Electricity and Magnetism']],
                'english tests': ['TOEFL iBT', 'IELTS (academic)', 'CPE', 'CAE'],
                'TOEFL iBT': [['overall', 80]],
                'IELTS (academic)': [['overall', 6.0]],
                'CPE': [['overall', 200]],
                'CAE': [['overall', 180]],
                'about': ['Mechanical Engineering', 'Technology', 'Society', 'Design', 'Physics'],
                'multidisciplinary': 'yes',
                'enterance exam': 'no',
                'study choice check': 'no',
                'research': 'no',
                'practical oriented': 'yes',  # hands-on/lab experience
                'project oriented': 'yes',
                'numerus fixus': 'no',
            },

            # VRIJE UNIVERSITEIT AMSTERDAM

        ]
        return kb
